servidor:
  nome: '&aBasicPvP'
  prefixo: '&f[{nome}&f]'
  databases:
    status:
      use-mysql: false
      host: ''
      port: 3306
      database: ''
      user: ''
      password: ''
informacoes:
  website: 'www.basicpvp.com.br'
  loja: '{website}/loja'
  discord: '{website}/discord'
aplicacoes:
  trialmod: '{website}/trialmod'
permissoes:
mensagens:
  motd: '{prefixo} &aEstamos esperando por você!'
  whitelist-motd: '{prefixo} &cServidor em manutenção.'
sidebar:
  kits:
    titulo: '{nome}'
    linhas:
    - ' '
    - ' Cargo: {player_group}'
    - ' Moedas: &6{player_coins}'
    - ' '
    - ' KillStreak: &7{player_killstreak}'
    - ' Abates: &7{player_kills}'
    - ' Mortes: &7{player_deaths}'
    - ' '
    - ' Kit: &a{player_kit}'
    - ' '
    - ' Rank: {player_rank}'
    - ' Jogadores: &7{server_players}/{server_slots}'
    - ' '
    - '&e{website}'
  warps:
    titulo: '{nome}'
    linhas:
    - ' '
    - ' Cargo: {player_group}'
    - ' Moedas: &6{player_coins}'
    - ' '
    - ' KillStreak: &7{player_killstreak}'
    - ' Abates: &7{player_kills}'
    - ' Mortes: &7{player_deaths}'
    - ' '
    - ' Warp: &a{player_warp}'
    - ' '
    - ' Rank: {player_rank}'
    - ' Jogadores: &7{server_players}/{server_slots}'
    - ' '
    - '&e{website}'
# TIPOS DE KIT: SIMULATOR, FULLIRON, PRESET01
# MODELO DO ITEM:
# material: TYPE,AMOUNT,DURABILITY
itens:
  geral:
    capacete: '&aCapacete'
    peitoral: '&aPeitoral'
    calca: '&aCalça'
    botas: '&aBotas'
    espada: '&aEspada'
    machado: '&aMachado'
    bussola: '&aBússola'
    pote: '&aPote'
    cogumelo-vermelho: '&aCogumelo'
    cogumelo-marrom: '&aCogumelo'
  spawn:
    kits:
      material: 'CHEST'
      display: '&aSeus Kits'
      slot: 4
    menu:
      material: 'NETHER_STAR'
      display: '&aMenu'
      slot: 5
    warps:
      material: 'COMPASS'
      display: '&aWarps'
      slot: 6
  arena: SIMULATOR
  fps: PRESET01
  1v1:
    modo: FULLIRON
    convidar:
      material: 'BLAZE_ROD'
      display: '&aConvidar para 1v1'
      slot: 4
    1v1-rapido:
      material: 'INK_SACK,1,8'
      display: '&a1v1 Rápido'
      slot: 6
    procurando-1v1-rapido:
      material: 'INK_SACK,1,10'
      display: '&aProcurando 1v1...'
icones:
  kits:
    pvp:
      material: 'STONE_SWORD'
      display: '&aKit PvP'
      lore:
      - '&7Mostre a verdadeira força da'
      - '&7sua Espada com Afiação I.'
      flags:
        hide-attributes: true
    anchor:
      preco: 450
      material: 'ANVIL'
      display: '&aKit Anchor'
      lore:
      - '&7Faça o PvP sem knockback'
      - '&7ser bem mais assustador'
      - '&7do que seu inimigo espera.'
    archer:
      preco: 375
      material: 'BOW'
      display: '&aKit Archer'
      lore:
      - '&7Seja um atirador de longa distância,'
      - '&7e mostre um estilo de combate diferente.'
    camel:
      preco: 350
      material: 'SAND'
      display: '&aKit Camel'
      lore:
      - '&7Seja mais forte no bioma de Deserto.'
    fisherman:
      preco: 750
      material: 'FISHING_ROD'
      display: '&aKit Fisherman'
      lore:
      - '&7A pescaria é uma arte com'
      - '&7habilidades misteriosas.'
    hulk:
      preco: 400
      material: 'DISPENSER'
      display: '&aKit Hulk'
      lore:
      - '&7Segure seus oponentes e faça com'
      - '&7que a pressão no combate aumente.'
    kangaroo:
      preco: 1000
      material: 'FIREWORK'
      display: '&aKit Kangaroo'
      lore:
      - '&7Aumente sua mobilidade'
      - '&7facilmente e destrua todos que'
      - '&7entrarem no seu caminho.'
    magma:
      preco: 600
      material: 'FIREBALL'
      display: '&aKit Magma'
      lore:
      - '&7Tenha 30% de chance de colocar'
      - '&7fogo nos seus oponentes.'
    monk:
      preco: 850
      material: 'BLAZE_ROD'
      display: '&aKit Monk'
      lore:
      - '&7Embaralhe o inventário dos seus'
      - '&7inimigos e os deixe confusos.'
    poseidon:
      preco: 900
      material: 'WATER_BUCKET'
      display: '&aKit Poseidon'
      lore:
      - '&7Entre na água e fique mais'
      - '&7forte e use sua força marítima'
      - '&7para vencer seus oponentes.'
    snail:
      preco: 600
      material: 'STRING'
      display: '&aKit Snail'
      lore:
      - '&7Faça com que seus inimigos'
      - '&7fiquem lentos.'
    switcher:
      preco: 850
      material: 'SNOW_BALL'
      display: '&aKit Switcher'
      lore:
      - '&7Troque de lugar com outras pessoas.'
    thor:
      preco: 750
      material: 'WOOD_AXE'
      display: '&aKit Thor'
      lore:
      - '&7Receba os poderes do Deus do Raio.'
      flags:
        hide-attributes: true
    viking:
      preco: 1000
      material: 'STONE_AXE'
      display: '&aKit Viking'
      lore:
      - '&7Mostre que um Machado é bem'
      - '&7mais poderoso que uma Espada.'
      flags:
        hide-attributes: true
    viper:
      preco: 600
      material: 'SPIDER_EYE'
      display: '&aKit Viper'
      lore:
      - '&7Faça com que seus inimigos'
      - '&7fiquem envenenados.'
  warps:
    1v1:
      material: 'BLAZE_ROD'
      display: '&aWarp 1v1'
      lore:
      - '&7Tenha duelos solo contra'
      - '&7outros jogadores.'
    fps:
      material: 'GLASS'
      display: '&aWarp FPS'
      lore:
      - '&7Jogue em um local mais limpo'
      - '&7e leve para otimizar seus FPS.'
    lava-challenge:
      material: 'LAVA_BUCKET'
      display: '&aWarp Lava Challenge'
      lore:
      - '&7Treine seu refil e seu recraft'
      - '&7enquanto completa desafios.'
  cabecas:
    bancada-de-trabalho:
      material: 'WORKBENCH'
      display: '&aBancada de Trabalho'
      lore:
      - '&7É usada para se fabricar itens,'
      - '&7responsável por ser a base'
      - '&7da evolução dos materiais.'
    vidro:
      material: 'GLASS'
      display: '&aVidro'
      lore:
      - '&7Utilizado em decorações para'
      - '&7se ver através de paredes e muros.'
    estante:
      material: 'BOOKSHELF'
      display: '&aEstante'
      lore:
      - '&7Utilizada para fazer'
      - '&7livrarias e bibliotecas.'
    dinamite:
      material: 'TNT'
      display: '&aDinamite'
      lore:
      - '&7Utilizada em mineração'
      - '&7e em trollagens.'
    gerador-de-monstros:
      material: 'MOB_SPAWNER'
      display: '&aGerador de Monstros'
      lore:
      - '&7Utilizado para fazer farms'
      - '&7e gerar monstros e animais.'
    bloco-de-diamante:
      material: 'DIAMOND_BLOCK'
      display: '&aBloco de Diamante'
      lore:
      - '&7Não possui um uso,'
      - '&7apenas para ostentação.'
    lampada-de-redstone:
      material: 'REDSTONE_LAMP_OFF'
      display: '&aLâmpada de Redstone'
      lore:
      - '&7Utilizada em sistemas para'
      - '&7identificar atividade.'
modelos:
  kit:
    selecionar:
      display: '{name}'
      lore:
      - '{description}'
      - ' '
      - '&eClique para selecionar'
    comprar:
      display: '{name}'
      lore:
      - '{description}'
      - ' '
      - '&7Preço: &f{price} Moedas&7.'
      - '&eClique para comprar'
  warp:
    display: '{name}'
    lore:
    - '{description}'
    - ' '
    - '&eClique para teleportar'
  cabeca:
    selecionar:
      display: '{name}'
      lore:
      - '&7{description}'
      - ' '
      - '&eClique para selecionar'
    sem-permissao:
      display: '{name}'
      lore:
      - '&7{description}'
      - ' '
      - '&cSem permissão para selecionar'
inventarios:
  menu-geral:
    perfil:
      material: 'SKULL_ITEM,1,3'
      display: '&aSeu Perfil'
      lore:
      - ' '
      - ' &fCargo: {player_group}'
      - ' &fMoedas: &6{player_coins}'
      - ' '
      - ' &fRank: {player_rank_icon} {player_rank}'
      - ' &fXP: &b{player_xp}'
      - ' '
      - ' &fKillStreak: &7{player_killstreak}'
      - ' &fAbates: &7{player_kills}'
      - ' &fMortes: &7{player_deaths}'
      - ' '
      slot: 11
    loja-de-kits:
      material: 'EMERALD'
      display: '&aLoja de Kits'
      lore:
      - '&7Compre Kits usando as moedas'
      - '&7que adiquiriu jogando.'
      slot: 13
    cabecas:
      material: 'LEATHER_HELMET'
      display: '&aCabeças'
      lore:
      - '&7Escolha um bloco e deixe'
      - '&7sua cabeça customizada.'
      slot: 15
    requisitos-youtuber:
      material: 'BOOK'
      display: '&aRequisitos para &bYouTuber&a:'
      lore:
      - ' '
      - ' &7Requisitos para canal:'
      - '  &7Mínimo de &f1.000 inscritos&7.'
      - '  &7Necessário ser um &fcanal ativo&7.'
      - '  &7Gravar um &fvídeo no servidor&7.'
      - ' &7Requisitos do vídeo:'
      - '  &7Mínimo de &f300 visualizações&7.'
      - '  &7Mínimo de &f50 gostei&7.'
      - '  &fIP do servidor na descrição.'
      slot: 17
placas:
  # HORIZONTAL, VERTICAL
  recraft-align: 'HORIZONTAL'
  recraft:
  - ' '
  - '&a&lRECRAFT'
  - '&7(Clique)'
  - ' '
  sopas:
  - ' '
  - '&a&lSOPAS'
  - '&7(Clique)'
  - ' '
  desafios:
    facil:
    - '&a&lDESAFIO:'
    - '&aFácil'
    - '&a&lCOMPLETO!'
    - '&7(Clique)'
    medio:
    - '&a&lDESAFIO:'
    - '&eMédio'
    - '&a&lCOMPLETO!'
    - '&7(Clique)'
    dificil:
    - '&a&lDESAFIO:'
    - '&cDifícil'
    - '&a&lCOMPLETO!'
    - '&7(Clique)'
    extremo:
    - '&a&lDESAFIO:'
    - '&8Extremo'
    - '&a&lCOMPLETO!'
    - '&7(Clique)'
premios:
  matar:
    moedas: 10
    xp: 3
  morrer:
    moedas: -5
    xp: -1
  facil:
    moedas: 5
    xp: 0
  medio:
    moedas: 10
    xp: 1
  dificil:
    moedas: 15
    xp: 3
  extremo:
    moedas: 25
    xp: 5
opcoes:
  mensagens:
    enviar-mensagem-de-xp: true
    enviar-mensagem-de-moedas: true
  desafios:
    anunciar-facil: false
    anunciar-medio: false
    anunciar-dificil: false
    anunciar-extremo: true