# SIMULATOR, FULLIRON
modo: 'SIMULATOR'
servidor:
  nome: '&aBasicPvP'
  prefixo: '&f[{nome}&f]'
informacoes:
  website: 'www.basicpvp.com.br'
  loja: '{website}/loja'
  discord: '{website}/discord'
aplicacoes:
  trialmod: '{website}/trialmod'
permissoes:
mensagens:
  cor-principal: '&a'
  motd: '{prefixo} &aEstamos esperando por você!'
  whitelist-motd: '{prefixo} &cServidor em manutenção.'
sidebar:
  kits:
    titulo: '{nome}'
    linhas:
    - ' '
    - ' Cargo: {player_group}'
    - ' Moedas: &6{player_coins}'
    - ' '
    - ' KillStreak: &7{player_killstreak}'
    - ' Abates: &7{player_kills}'
    - ' Mortes: &7{player_deaths}'
    - ' '
    - ' Kit: &a{player_kit}'
    - ' '
    - ' Rank: {player_rank}'
    - ' Jogadores: &7{server_players}/{server_slots}'
    - ' '
    - '&e{website}'
  warps:
    titulo: '{nome}'
    linhas:
    - ' '
    - ' Cargo: {player_group}'
    - ' Moedas: &6{player_coins}'
    - ' '
    - ' KillStreak: &7{player_killstreak}'
    - ' Abates: &7{player_kills}'
    - ' Mortes: &7{player_deaths}'
    - ' '
    - ' Warp: &a{player_warp}'
    - ' '
    - ' Rank: {player_rank}'
    - ' Jogadores: &7{server_players}/{server_slots}'
    - ' '
    - '&e{website}'
# TIPOS DE KIT: SIMULATOR, FULLIRON, PRESET01
# MODELO DO ITEM:
# material: TYPE,AMOUNT,DURABILITY
itens:
  geral:
    capacete: '&aCapacete'
    peitoral: '&aPeitoral'
    calca: '&aCalça'
    botas: '&aBotas'
    espada: '&aEspada'
    bussola: '&aBússola'
    pote: '&aPote'
    cogumelo-vermelho: '&aCogumelo'
    cogumelo-marrom: '&aCogumelo'
  spawn:
    kits:
      material: 'CHEST'
      display: '&aSeus Kits'
      slot: 3
    menu:
      material: 'NETHER_STAR'
      display: '&aMenu'
      slot: 4
    warps:
      material: 'COMPASS'
      display: '&aWarps'
      slot: 5
  arena: SIMULATOR
  fps: PRESET01
  1v1: FULLIRON
inventarios:
  menu-geral:
    perfil:
      material: 'SKULL_ITEM,1,3'
      display: '&aSeu Perfil'
      lore:
      - ' '
      - ' &fCargo: {player_group}'
      - ' &fMoedas: &6{player_coins}'
      - ' '
      - ' &fRank: {player_rank_icon} {player_rank}'
      - ' &fXP: &b{player_xp}'
      - ' '
      - ' &fKillStreak: &7{player_killstreak}'
      - ' &fAbates: &7{player_kills}'
      - ' &fMortes: &7{player_deaths}'
      - ' '
      slot: 11
    loja-de-kits:
      material: 'EMERALD'
      display: '&aLoja de Kits'
      lore:
      - '&7Compre Kits usando as moedas'
      - '&7que adiquiriu jogando.'
      slot: 13
    cabecas:
      material: 'LEATHER_HELMET'
      display: '&aCabeças'
      lore:
      - '&7Escolha um bloco e deixe'
      - '&7sua cabeça customizada.'
      slot: 15
    requisitos-youtuber:
      material: 'BOOK'
      display: '&aRequisitos para &bYouTuber&a:'
      lore:
      - ' '
      - ' &7Requisitos para canal:'
      - '  &7Mínimo de &f1.000 inscritos&7.'
      - '  &7Necessário ser um &fcanal ativo&7.'
      - '  &7Gravar um &fvídeo no servidor&7.'
      - ' &7Requisitos do vídeo:'
      - '  &7Mínimo de &f300 visualizações&7.'
      - '  &7Mínimo de &f50 gostei&7.'
      - '  &fIP do servidor na descrição.'
      slot: 17