servidor:
  nome: '&aBasicPvP'
  prefixo: '&f[{nome}&f]'
informacoes:
  website: 'www.basicpvp.com.br'
  loja: '{website}/loja'
  discord: '{website}/discord'
aplicacoes:
  trialmod: '{website}/trialmod'
mensagens:
  cor-principal: '&a'
  motd: '{prefixo} &aEstamos esperando por você!'
  whitelist-motd: '{prefixo} &cServidor em manutenção.'
permissoes:
itens:
  peitoral: '{cor_principal}Peitoral'
  espada-de-pedra: '{cor_principal}Espada'
  bussola: '{cor_principal}Bússola'
  pote: '{cor_principal}Pote'
  cogumelo-vermelho: '{cor_principal}Cogumelo'
  cogumelo-marrom: '{cor_principal}Cogumelo'