servidor:
  nome: '&aBasicPvP'
  prefixo: '&f[{nome}&f]'
informacoes:
  website: 'www.basicpvp.com.br'
  loja: '{website}/loja'
  discord: '{website}/discord'
aplicacoes:
  trialmod: '{website}/trialmod'
mensagens:
  cor-principal: '&a'
  motd: '{prefixo} &aEstamos esperando por você!'
  whitelist-motd: '{prefixo} &cServidor em manutenção.'
permissoes:
itens:
  peitoral: '{cor_principal}Peitoral'
  espada-de-pedra: '{cor_principal}Espada'
  bussola: '{cor_principal}Bússola'
  pote: '{cor_principal}Pote'
  cogumelo-vermelho: '{cor_principal}Cogumelo'
  cogumelo-marrom: '{cor_principal}Cogumelo'
sidebar:
  kits:
    titulo: '{nome}'
    linhas:
    - ' '
    - ' Cargo: {player_group}'
    - ' Moedas: &6{player_coins}'
    - ' '
    - ' KillStreak: &7{player_killstreak}'
    - ' Abates: &7{player_kills}'
    - ' Mortes: &7{player_deaths}'
    - ' '
    - ' Kit: {cor_principal}{player_kit}'
    - ' '
    - ' Rank: {player_rank}'
    - ' Jogadores: &7{server_players}/{server_slots}'
    - ' '
    - '&e{website}'
  warps:
    titulo: '{nome}'
    linhas:
    - ' '
    - ' Cargo: {player_group}'
    - ' Moedas: &6{player_coins}'
    - ' '
    - ' KillStreak: &7{player_killstreak}'
    - ' Abates: &7{player_kills}'
    - ' Mortes: &7{player_deaths}'
    - ' '
    - ' Warp: {cor_principal}{player_warp}'
    - ' '
    - ' Rank: {player_rank}'
    - ' Jogadores: &7{server_players}/{server_slots}'
    - ' '
    - '&e{website}'