main: com.github.caaarlowsz.basicpvp.BasicKitPvP
name: BasicPvP
version: 0.6.0
description: Minecraft Bukkit Basic PvP Plugin.
author: Carlos Henrique#0240
depend: [NametagEdit]
commands:
  admin:
    description: Use este comando para entrar no/sair do Modo Admin.
    usage: /<command>
    aliases: [admmode, adminmode, staffmode]
  apply:
    description: Use este comando para ver as aplicações.
    usage: /<command>
    aliases: [applications, aplicar, aplicacoes]
  broadcast:
    description: Use este comando para anunciar mensagens.
    usage: /<command> (Mensagem)
    aliases: [bcast, bc, anuncio, anunciar, aviso]
  build:
    description: Use este comando para poder construir.
    usage: /<command> (ON, OFF)
  cage:
    description: Use este comando para prender jogadores.
    usage: /<command> (Nickname)
    aliases: [jaula, prender]
  chat:
    description: Use este comando para manipular o Chat do Servidor.
    usage: /<command> (ON, OFF)
  fly:
    description: Use este comando para habilitar/desabilitar o vôo de jogadores.
    usage: /<command> [Nickname]
    aliases: [voar]
  gamemode:
    description: Use este comando para alterar o modo de jogo.
    usage: /<command> (Modo de Jogo)
    aliases: [gmode, gm]
  info:
    description: Use este comando para saber informações do Servidor.
    usage: /<command>
    aliases: [informations, information, informacoes, infos]
  inventorysee:
    description: Use este comando para ver o inventário de jogadores.
    usage: /<command> (Nickname)
    aliases: [invsee, inv]
  kit:
    description: Use este comando para selecionar um kit.
    usage: /<command> (Nome do Kit)
  ping:
    description: Use este comando para ver o ping de um jogador.
    usage: /<command> [Nickname]
    aliases: [latency, lat]
  rank:
    description: Use este comando para ver os ranks do servidor.
    usage: /<command>
    aliases: [ranks, ligas, liga]
  report:
    description: Use este comando para denunciar jogadores.
    usage: /<command> (Nickname) (Motivo)
    aliases: [reportar, denunciar, rep, r]
  set:
    description: Use este comando para definir locais.
    usage: /<command> (Nome do Local)
  spawn:
    description: Use este comando para ir até o Spawn.
    usage: /<command>
    aliases: [respawn, kill]
  tag:
    description: Use este comando para alterar sua Tag.
    usage: /<command> (Nome da Tag)
  teleport:
    description: Use este comando para se teleportar jogadores ou até locais.
    usage: /<command> (Nickname) [Nickname] ou /<command> (X) (Y) (Z)
    aliases: [tp]
  teleporthere:
    description: Use este comando para teleportar jogadores até você.
    usage: /<command> (Nickname)
    aliases: [teleporth, tphere, tph]
  tell:
    description: Use este comando para enviar mensagens privadas.
    usage: /<command> (ON, OFF) ou /<command> (Nickname) (Mensagem)
    aliases: [whispers, whisper, w, msg]
  warp:
    description: Use este comando para ir até uma Warp.
    usage: /<command> (Nome da Warp)