main: com.github.caaarlowsz.basicpvp.BasicKitPvP
name: BasicPvP
version: 0.4.0
description: Minecraft Bukkit Basic PvP Plugin.
author: Carlos Henrique#0240
depend: [NametagEdit]
commands:
  build:
    description: Use este comando para poder construir.
    usage: /<command> (ON, OFF)
  chat:
    description: Use este comando para manipular o Chat do Servidor.
    usage: /<command> (ON, OFF)
  tell:
    description: Use este comando para enviar mensagens privadas.
    usage: /<command> (ON, OFF) ou /<command> (Nickname) (Mensagem)
    aliases: [whispers, whisper, w, msg]